@startuml
'https://plantuml.com/class-diagram

'left to right direction

package sensors_package as "Sensors" {

enum SensorStateEnum {
    DISARMED
    ARMED
    TRIGGERED
}

class Sensor extends Observable {
    + arm(Sensor sensor) : boolean
    + trigger(Sensor sensor) : boolean
    + reset(Sensor sensor) : boolean
    + disarm(Sensor sensor) : boolean
}

abstract class SensorState {
    + getState() : SensorStateEnum

    + arm(Sensor sensor) : boolean
    + trigger(Sensor sensor) : boolean
    + reset(Sensor sensor) : boolean
    + disarm(Sensor sensor) : boolean
}

class SecurityAlarm implements Observer {
    - String location
    - boolean isOn

    + update(Observable sensor, Object argument) : void
}

}

@enduml