@startuml
'https://plantuml.com/class-diagram

left to right direction
hide empty members

package request_package as "Request" {

    interface RequestType

    class Request {
    }

}

package agent_package as "Agent" {

    abstract class Agent {
        # Agent()
        # {static} String getNonAttendedResponse()
        # {abstract} String getRole()
        # Agent getSuperiorAgent()
        # void setSuperiorAgent(Agent superiorAgent)
        + String handleRequest(Request request)
        # {abstract} String respond(Request request)
    }
    Agent "1" --> "0..1" Agent : has a superior
    Agent "1" --> "0..*" RequestType : handles

    class Chatbot extends Agent {
        + public Chatbot(Agent superiorAgent)
        # String getRole()
        # String respond(Request request)
    }

    class Attendant extends Agent {
        + public Attendant(Agent superiorAgent)
        # String getRole()
        # String respond(Request request)
    }

    class Technician extends Agent {
        + public Technician(Agent superiorAgent)
        # String getRole()
        # String respond(Request request)
    }

}

package organization_package as "Organization" {

    interface Organization {
        String getName()
        String receiveComplaint(String complaint)
        String receiveQuestion(String question)
        String receiveRefundRequest(String description)
    }

}

@enduml
