@startuml
'https://plantuml.com/state'-diagram

hide empty description

[*] --> Disarmed

Disarmed --> Armed : User turns the system on

Armed --> Triggered : Sensor triggers the alarm
Armed --> Disarmed: User turns the system off

Triggered --> Armed : User resets the alarm

Disarmed --> [*]

@enduml
